language: node_js
node_js: '12'
cache:
  - yarn
  directories:
    - node_modules

before_install:
  - yarn install

jobs:
  include:
    - stage: linting
      script: yarn prettier
    - stage: unit testing
      script: yarn test
