language: node_js
node_js: '12'

addons:
  apt:
    packages:
      - libgconf-2-4

cache:
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache
    - node_modules

before_install:
  - yarn install
  - yarn run create

jobs:
  include:
    - stage: linting
      script: yarn prettier
    - stage: unit testing
      script: yarn test
    - stage: integration testing
      script: yarn run cy:ci
